# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: quintinchan
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: serverless-go-rest-api
service: serverless-gin
plugins:
  - serverless-dotenv-plugin
useDotenv: true

provider:
  name: aws
  runtime: provided.al2023
  region: ap-southeast-2
  stage: dev
  
functions:
  api:
    memorySize: 3008
    timeout: 10
    handler: bootstrap
    events:
      - http:
          path: /api/hc
          method: GET
          cors: true
      - http:
          path: /api/v1/jwt/refresh
          method: GET
          cors: true
      - http:
          path: /api/v1/order
          method: GET
          cors: true
      - http:
          path: /api/v1/user
          method: GET
          cors: true
      - http:
          path: /api/v1/user/pos
          method: GET
          cors: true
      - http:
          path: /api/v1/register
          method: POST
          cors: true
      - http:
          path: /api/v1/login
          method: POST
          cors: true
      - http:
          path: /api/v1/order/create
          method: POST
          cors: true
      - http:
          path: /api/v1/user/update/password
          method: POST
          cors: true
      - http:
          path: /api/v1/user/update/userinfo
          method: POST
          cors: true
      - http:
          path: /api/v1/user/addbalance
          method: POST
          cors: true
      - http:
          path: /api/v1/order/{oid}/cancel
          method: POST
          cors: true
          request: 
            parameters: 
              paths: 
                oid: true 
      - http:
          path: /api/v1/order/{oid}
          method: GET
          cors: true
          request: 
            parameters: 
              paths: 
                oid: true
    vpc:
      securityGroupIds:
        - sg-01db6966e5c05d8ab
      subnetIds:
        - subnet-08629b19764802ff3

package:
  patterns:
    - '!*/**'
    - bin/*